### PR TITLE
Bump version to 0.22.0, update changelog

### PR DESCRIPTION
**Pull request by colszowka**
Contains most notably #1035 and #1037, as well as a number of tweaks to rubocop + gitlab actions changes

### CODE REVIEW

**Comment by colszowka** [comment]
@deivid-rodriguez I'll follow up here on the thread from https://github.com/simplecov-ruby/simplecov/pull/1040#issuecomment-1364287968 since it probably belongs into here rather. Thanks, I was wondering if it might be due to those test projects in there. I ran bundle lock on the 3 related files, we shall see. Thanks a lot for your support!

**Comment by deivid-rodriguez** [comment]
That apparently didn't work :(

**Comment by colszowka** [comment]
@deivid-rodriguez Actually, this seems to have been the issue: https://github.com/simplecov-ruby/simplecov/pull/1041/commits/26407f17a7df725ab26a4faa9f2359e3484ba93d

Gotta sit out jruby finishing up, but everything else is green again. Thanks so much for jumping in to help here! :tada:

**Comment by colszowka** [comment]
Aand released :tada: https://rubygems.org/gems/simplecov/versions/0.22.0

**Pull request merged**
