### PR TITLE
Switch to cuprite to avoid failures with new Chrome

### LINKED ISSUE #925: Cucumber tests failing in main branch
For some reason cucumber tests are failing for me when I run them locally in main branch. For example, I currently have a clean local copy on commit 9cd3a46169943f2c79d688d96e93871cd7febe2d and here is what I get:

```
$ be cucumber features/old_version_json.feature:12
Using the default profile...
....F

(::) failed steps (::)

Ambiguous match, found 3 elements matching visible css " .t-line-summary" (Capybara::Ambiguous)
./features/step_definitions/html_steps.rb:55:in `/^I should see a (.+) coverage summary of (\d+)\/(\d+)( for the file)?$/'
features/old_version_json.feature:18:in `I should see a line coverage summary of 8/9'

Failing Scenarios:
cucumber features/old_version_json.feature:12 # Scenario: Running the tests succeeds

1 scenario (1 failed)
5 steps (1 failed, 4 passed)
0m6.321s
```

It looks like I have wrong version of simplecov-html, but it's locked to 0.12.2 in the Gemfile.
Build fails on Github as well: https://github.com/umbrellio/simplecov/runs/1063083286 (I just pushed the main branch to the forked repo).

Any ideas how to fix that?

### PR DESCRIPTION
**Pull request by PragTob**
Fixes #925
Ref: https://github.com/twalpole/apparition/issues/64

### CODE REVIEW

**Comment by PragTob** [comment]
```
(::) failed steps (::)

Browser did not produce websocket url within 2 seconds (Ferrum::ProcessTimeoutError)
./features/step_definitions/web_steps.rb:11:in `/^I open the coverage report$/'
./features/step_definitions/simplecov_steps.rb:31:in `/^I open the coverage report generated with `([^`]+)`$/'
features/branch_coverage.feature:17:in `I open the coverage report generated with `bundle exec rspec spec`'

Failing Scenarios:
cucumber features/branch_coverage.feature:9 # Scenario: 

76 scenarios (1 failed, 75 passed)
478 steps (1 failed, 9 skipped, 468 passed)
2m45.377s
##[error]Process completed with exit code 1.
```

😱

**Comment by PragTob** [comment]
Same error same scenario again.. worked locally. Maybe just increasing the timeout helps, will try later.

**Comment by PragTob** [comment]
Jim, we have to go slower!

Slower?

EVEN SLOWER

```
sing the default profile...
..F---------F.....F---.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................

(::) failed steps (::)

Browser did not produce websocket url within 5 seconds (Ferrum::ProcessTimeoutError)
./features/step_definitions/web_steps.rb:11:in `/^I open the coverage report$/'
./features/step_definitions/simplecov_steps.rb:31:in `/^I open the coverage report generated with `([^`]+)`$/'
features/branch_coverage.feature:17:in `I open the coverage report generated with `bundle exec rspec spec`'

Timed out waiting for response. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the :timeout option to a higher value might help. (Ferrum::TimeoutError)
./features/step_definitions/web_steps.rb:11:in `/^I open the coverage report$/'
./features/step_definitions/simplecov_steps.rb:31:in `/^I open the coverage report generated with `([^`]+)`$/'
features/config_autoload.feature:35:in `I open the coverage report generated with `bundle exec rspec spec`'

Failing Scenarios:
cucumber features/branch_coverage.feature:9 # Scenario: 
cucumber features/config_autoload.feature:17 # Scenario: 

76 scenarios (2 failed, 74 passed)
478 steps (2 failed, 12 skipped, 464 passed)
3m17.047s
##[error]Process completed with exit code 1.
```

**Comment by tycooon** [comment]
Looks like you are close to success 👍

**Comment by PragTob** [comment]
@tycooon not too sure about that :grin: 

I'm afraid that this is the intermittent failure which is the reason we switched from cuprite to apparition:

```
 Browser is dead or given window is closed (Ferrum::DeadBrowserError)
./features/step_definitions/web_steps.rb:11:in `/^I open the coverage report$/'
./features/step_definitions/simplecov_steps.rb:31:in `/^I open the coverage report generated with `([^`]+)`$/'
features/config_styles.feature:38:in `I open the coverage report generated with `bundle exec rake test`'
```

@deivid-rodriguez ? :grin:

**Comment by PragTob** [comment]
I mean... at least this one is different by I have no idea why:

```
expected to find visible css ".header h3" with text "lib/faked_project/some_class.rb" but there were no matches. Also found "lib/faked_project/framework_specific.rb", "lib/faked_project/meta_magic.rb", "lib/faked_project/some_class.rb", "spec/forking_spec.rb", "spec/meta_magic_spec.rb", "spec/some_class_spec.rb", "lib/faked_project.rb", which matched the selector but not all filters.  (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/html_steps.rb:63:in `/^I open the detailed view for "(.+)"$/'
features/branch_coverage.feature:33:in `I open the detailed view for "lib/faked_project/some_class.rb"'

Failing Scenarios:
cucumber features/branch_coverage.feature:9 # Scenario: 

76 scenarios (1 failed, 75 passed)
478 steps (1 failed, 4 skipped, 473 passed)
3m24.379s
```

This one is still "muh browser dead":

```
Browser is dead or given window is closed (Ferrum::DeadBrowserError)
./features/step_definitions/web_steps.rb:11:in `/^I open the coverage report$/'
./features/step_definitions/simplecov_steps.rb:31:in `/^I open the coverage report generated with `([^`]+)`$/'
features/test_unit_groups_and_filters_complex.feature:29:in `I open the coverage report generated with `bundle exec rake test`'

Failing Scenarios:
cucumber features/test_unit_groups_and_filters_basic.feature:10 # Scenario: 
cucumber features/test_unit_groups_and_filters_complex.feature:12 # Scenario: 
```

There are some freedom patches on cuperite to force a page reload after every visit that seems to fix it... maybe that's the better route. Sigh.

**Comment by deivid-rodriguez** [comment]
I don't recall the actual errors, I should've noted them :disappointed:.

**Comment by PragTob** [comment]
I... still have no idea how to fix this other than downgrading Chrome for CI and for everyone. Cuperite/ferrum isn't working for reasons I seem to be unable to fix... there's a hack for apparition for which we could go but overall a library essential for our tests being broken for so long doesn't give me high confidence (and sucks) could switch to selenium... but yeah.

**Comment by PragTob** [comment]
Tried selenium-webdriver... gives me element obscured when trying to close the detailed view and I have no idea why :(

**Comment by PragTob** [comment]
Apparently CI is working again through the magic of Chrome updates. Closing this.

**Pull request closed without merging**
